id: 4106cadbd69f41faa3efb0a7aae44b19
initial_creation_type: ocr
source_metadata:
  volumes:
    cae12955db60486a83047ba3eae9435b:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
